# .github/workflows/download-book.yml
name: Download Book3.bin to engines

on:
  workflow_dispatch:

jobs:
  download-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo with PAT
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Download Book3.bin from GitHub
      run: |
        mkdir -p engines
        curl -L -o engines/Optical.bin "https://raw.githubusercontent.com/Chess75/TheBestb/main/engines/Book3.bin"

    - name: Commit & push Optical.bin
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add engines/Optical.bin
        git commit -m "Add Optical.bin from Book3.bin" || echo "No changes to commit"
        git push "https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}" HEAD:main
