# .github/workflows/add-optical.yml
name: Add Optical.bin to engines

on:
  workflow_dispatch:        # run it manually from the Actions tab
  push:
    paths:
      - ".github/workflows/add-optical.yml"   # re-runs if you edit this file

jobs:
  download-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download Optical.bin from MediaFire
      run: |
        mkdir -p engines
        # follow redirects (-L) to grab the file
        curl -L -o engines/Optical.bin "https://download1477.mediafire.com/nribl7djot5g/6dnw9v6lyo18lw5/Optical.bin"

    - name: Commit & push the new file
      run: |
        git config user.name  "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add engines/Optical.bin
        git commit -m "Add Optical.bin to engines folder" || echo "Nothing to commit"
        git push
