name: Update Stockfish to Latest Build

on:
  workflow_dispatch:       # Manual run from GitHub Actions tab
  schedule:
    - cron: '0 0 * * *'     # Optional: runs daily at midnight UTC

permissions:
  contents: write

jobs:
  update-stockfish:
    name: Download & Push Latest Stockfish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Fetch latest AVX2 build URL
        id: fetch
        run: |
          URL=$(curl -s https://abrok.eu/stockfish/ | grep -Eo 'href="[^"]*linux64avx2/stockfish_[^"]+\.zip"' | head -n 1 | cut -d'"' -f2)
          echo "download_url=https://abrok.eu${URL}" >> $GITHUB_OUTPUT

      - name: Download latest Stockfish build
        run: |
          curl -L -o stockfish.zip "${{ steps.fetch.outputs.download_url }}"

      - name: Unzip Stockfish
        run: unzip -q stockfish.zip

      - name: Move and rename Stockfish binary
        run: |
          BIN_PATH=$(find . -type f -executable -name "stockfish_*_x64_avx2" | head -n 1)
          if [[ -z "$BIN_PATH" ]]; then
            echo "❌ Stockfish binary not found!"
            exit 1
          fi
          mv "$BIN_PATH" engines/stockfish
          chmod +x engines/stockfish

      - name: Commit and push if updated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git diff --quiet engines/stockfish; then
            echo "✅ No changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add engines/stockfish
          git commit -m "chore: update to latest Stockfish build"
          git push
